//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISAutobuskaStanica.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutobuskaStanicaModelContainer : DbContext
    {
        public AutobuskaStanicaModelContainer()
            : base("name=AutobuskaStanicaModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AutobuskaStanica> AutobuskaStanicas { get; set; }
        public virtual DbSet<RedVoznje> RedVoznjes { get; set; }
        public virtual DbSet<VoznaSezona> VoznaSezonas { get; set; }
        public virtual DbSet<Ugovor> Ugovors { get; set; }
        public virtual DbSet<AutobuskiPrevoznik> AutobuskiPrevozniks { get; set; }
        public virtual DbSet<Autobus> Autobus { get; set; }
        public virtual DbSet<Vozac> Vozacs { get; set; }
        public virtual DbSet<Linija> Linijas { get; set; }
        public virtual DbSet<PregledLinija> PregledLinijas { get; set; }
    }
}
